#Application Configuration
#port: ${PORT:0}
server:
  port: 8090
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhos:8761/eureka
    instance-id:
      ${spring.application.name}:
        ${spring.application.instance_id: ${random.value}}


spring:
  cloud:
    gateway:
      routes:
        - id: infomediaservice_login-server
          uri: lb://infomediaservice_login-application
          predicates:
            - Path=/api/v1/security/**
          filters:
            - StripPrefix=3
        - id: infomediaservice_usuario-application
          uri: lb://infomediaservice_usuario-application
          predicates:
            - Path=/api/v1/usuarios/**
          filters:
            - StripPrefix=3
        - id: infomediaservice_signatures-server
          uri: lb://infomediaservice_signatures-application
          predicates:
            - Path=/api/v1/signatures/**
          filters:
            - StripPrefix=3
            - AddResquestHeader=token-request, 123456
            - AddResponseHeader=token-response, 12345678
            - AddResquestParameter=nombre, andres
        - id: infomediaservice_vuplaform-application
          uri: lb://infomediaservice_vuplaform-application
          predicates:
            - Path=/api/v1/vuplaform/**
          filters:
            - StripPrefix=3
            - name: CircuitBreacker
              args:
                name: vuplaform
                statusCodes: 500
                fallbackUri: forward:/api/v1/vuplaform
                #servicio alternativo puede ser un tema de trata de errores
  sleuth:
    sampler:
      probability: 1.0


resilience4j:
  circuitbreaker:
    configs:
      defecto:
        sliding-window-size: 6
        failure-rate-threshold: 50
        wait-duration-in-open-state: 20s
        permitted-number-of-calls-in-half-open-state: 4
        slow-call-rate-threshold: 50
        slow-call-duration-threshold: 2s
    instances:
      vuplaform: ##nombre que le ponemos a la configuracion y lo ponemos en el controlador
        base-config: defecto
  timelimiter:
    configs:
      defecto:
        timeout-duration: 6s
    instances:
      vuplaform:
        base-config: defecto
