#Application Configuration
server:
  port: 8082
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance-id:
    ${spring.application.name}:
      ${spring.application.instance_id: ${random.value}}

  main:
    allow-bean-definition-overriding: true


spring:
  sleuth:
    sampler:
      probability: 1.0
    base-url: http://localhost:9411/
