server:
  port: 8888
spring:
  #profiles:
  #active: "@spring.profile.active@"

  application:
    name: config-server

  config:
    name: config-server

      #security:
    # user:
    #  name: "@security.user.name@"
    # password: "@security.user.password@"

  cloud:
    config:
      server:
        git:
          uri: ${AC_CONFIG_SERVICE_GIT_REMOTE_URI}
          default-label: "master"
          search-paths: "config-data"
          refresh-rate: 30
          ignore-local-ssh-settings: true
          strict-host-key-checking: false
          clone-on-start: true
          force-pull: true
          delete-untracked-branches: true
          host-key: ${HOSTKEY}
          host-key-algorithm: ssh-rsa
          passphrase: ${PASSPHRASE}
          private-key: |
            -----BEGIN RSA PRIVATE KEY-----
            Proc-Type: 4,ENCRYPTED
            DEK-Info: AES-128-CBC,A3E666C359A9E8397811EFDA9DF0520A
            
            8bb2Xb/BHsBqT59k7DikDOcqiA50Aw2G8KAlhEl1iYrRcSuCgBxr3mryulDzWGfy
            KUu0i0hvtVrEv77Iliy/o5Gd6cfR+4vymvFosuSaADR1uXZCSO9yiGGajgo8vRNy
            dud/J8a8jhCZ0mA6wlRpRQymZwM8nfJcaTJ7YysAUKdmw6lop1XMDMIpu/EV9R+D
            vxREjEIADtVOieUG96BvGKsEduUkJM9SDlRaU3XuKkW5aeAbiKeZGPNhmYbYgHfg
            Y27izFuVY7slhHU9dAORw7Fsrf8fgj3sL2gThjc/M3uTueCtUkruRTUngEh6SIGx
            kUAfcltTT6JbT0ZzWhxdXAwXhRM4hbQgZRCVAuTiMWDChNHTPX3ahYCBqlQhljRm
            bm3rgBMT3ZpNjartnwk3+lgnLDvidWOdJg6hbZQNtXNUiaGh02IC+BepL7l2TdWT
            DxuzQejNBIYZyahgjMEFKxAdqd5I+cX/6Dlev9qnxk5wOUsdFwWES9IlH99iJz6+
            aXv8G/ooqbzniqPYA274XbOjbTrOS27K3Qftji6wTxwkvfCZYaPnBdrlikHz2B6w
            +kBPBJ4QBykGXb8Re3IXZnUImmLknY5+Jko0kzymjzYKuCyk02pht0qeqzmfl+CB
            jVwPGfNQaUAMCqsEWNIiDmU80gsi6PoOAc4zPfCGVobKfCP9CkZZ9Xn28W4acKNi
            eoPvRZl8X+4BCjQL/2bPUjerr1YELwgs4lotXkHwnTp0vQU0WVqhxCRVqhHK3OAP
            D8UvXT5VksrCJjR2J/nFkonk6cK8ftvBqD8TVuCwK7Gap8fPGPhZzb8zGE/krzrp
            G1an0qg+d8IohlQVEVm+wN+LdbqQ9CU7XknKDljnFuGFCn/Z8Axrcln6YmNBs0tu
            14QAc/Nevce3cjQhAepIUWsgtV5bUfri7m4ZSwVkM1bJnFThxlxTEappem9UKk2P
            mF8aDFQG1hUnfCAki9YzgpYhL2seYNC4ufF0JJdheZA0ipWlagTFatef26AcPvld
            z37Zg92fzzec4SXAn67kKTGQI4ForDeJrMAax3KCiQtz9N1T4QzhODH4Mkf4IsDe
            d53dMWoa+qlbPbf159MYOWxUn6tI1voNJgmu2oGlWdWowNp8sODzNqDReQotprsi
            f7gWQQ/y0jKIDPh+QTnSn1MI+Vt7Y9z0BHcpkwXsIdLNDIs7e/dXHvT4lCDZvW8P
            DPhEZZ3osXYNQgluzaYUB+OmWqbOmeDGRCbvDhHgb0ZDhwUX9Q8WMftaF2mJyAXv
            VuWZxv/J2hEYzuWg8aODWPM+Mrfy0Sc+Gg9jmxyQFpO6+6962QT2DERqfLzA6+nV
            qCcjiOLrjuR4qFMNO69Bb1JUzzT4VIao/OK3+e8xpe143E9+au1l8YErflEptzQI
            dWQDjhZPg1waVEUWqm3pvXqZGNRaMjTsdPF9RHRXEXD1OLmFkoVVT27Zwn5gPeYa
            f0QRQlbNeW8l3Yk18XvjDxhqMzmt+6A7oTGOP8T67ExrkphyBBzDWRS+tbZi9Yrh
            ktZfr8kXxiAFy04Fjn9HXYjHKyQcj4NXC6rieSHvusgEEfCQmd2osZXShKq729gG
            IYKEixAZorFqRMpcxn+iff8zeIbDKQyphtIq1r61b5CAYRK4KkpDFQ8YdhroZAnb
            +3Y+/xUxGW/yjj6SgZbtYp8ARwNP04amcTiMNf8xPzU7M3RSsE3s2d/SYxVGCBp5
            B5K+7UvdlcILEvyhk1NqRvsamyE0rqn52iR/NjbAcxfZCBoDVT5qWR5CjgHmBpjr
            kzJuG8V8AvKozS2sD6V+ZIhsDDMx9Y2wgjA6d5hHPdTcwke1qial/c7DOC6N9JRH
            GlUocSNMRBTbvpH67kFKyMDsRGHzGfOrbT2zQ5QjMmNhqhP4sYYzVctt1sZzvFqY
            UARcpvMqIbFt2l3en0k/Z1PsYISV97cHmysJg5CyGFUejk0buUnvFVWNZMj0xZJa
            gbxm32JS1tyeSfu5XYDisMjl7hPob0v1fWqFhGU1Nhh4zriI6rQRPyeoPTJxPmeq
            BvE80SI1hFp5ajI+vo5RtMwi+BsY6hsnNmnQU9SxMjLVgIxFgc/3USBvcbvCnXsc
            rcJW4VTB4SEMzg73SYbMR8NZiYmUDCKPE8uOgKAzR91uDv34xmQZog+gcya4K7Al
            jUJYj4FOet49S76d3+qPAHCZyFRYxOIL9Up2z3ylNtY3tZAwiO+YIJBGT0lt0R6q
            11DewdzFiwBWQtgr5uUtJP8wpbQK1T8lzEpruhxbXsVU/6/gCYapxTc/xWAlKZI7
            phEUV5TIzqh6ZX3SSBoBh377kVB5dERAj4H0J7G9MMlBy8DlJ5OBFK3Bkhu8DpA7
            PvqDQoY+jlW1mlt7aVn3B7xMt8HZLEaDqF6iHvfuLcfFptRvDbt1URpvU0+CSN68
            CpO2tp0IXg9f/wsztKW4ut1dYSKNgmEaX0/cw4abAPya54lAFl3usYsdM/GeXpbQ
            TtPQrsKbTC6xklSN1ppjgknRfinp6QYDwDLt/xmD8xBoyR/Z+aH4KW3RM2aO37mQ
            hanhRo4PDstMfT+IaWttbOetnm3JlrRe44hLBhByzwNUQ5B6T93tM7b3I+qlwsxu
            P7O6C4VoHKs/LfnBs3r9po1+tBn5imG1X7eJr8mYBE5GDDCnNLFuST9dKgwOlWxJ
            KfCTcsEv72dgnDwW721SPt9n6oSR0iZGoNxwyi228wEh5J6ht8WsdItxv7rI2JkU
            NYAKjmHjRmA2kYPlUVUKI+bqjnqcDT7PYGwNIvb5BihwfT9OpPnwhjqaDuZ1dZHh
            thNCObt7C2tI/aX6uZ0OVLA4GdElUewMPbWjGFwNbsCm3cDrXVjPMGZQK4HrD7Om
            hU8NjRT2P/k/4GCd1lTwbm6KFvUGYM1z8SE/n97Gm8WarD52JqWNzlMlnm0mefPY
            RipgNObe6sEAXm5e1MUyQtmeQDK4f9WpMbwyuUhP+ZzYwYt26OBA4/g/GycCk5Wz
            GLHfCqcwIJb49NuCutsBjNW/gLcpW5ZtKRk84agMbBUe6m41kxFNQZuAp50388dU
            /l6Vz6rm12jDkwm/qrMOhM93giOXG2vaCIlWATLfEEJ0Nt6dh8LK+1aKzVTG5R/J
            -----END RSA PRIVATE KEY-----
---
