server:
  port: 8888

spring:
  application:
    name: config-server
  config:
    name: config-server
  sleuth:
    sampler:
      probability: 1.0

  cloud:
    config:
      server:
        git:
          uri: ${AC_CONFIG_SERVICE_GIT_REMOTE_URI}
          default-label: "master"
          search-paths: "config-data/local"
          clone-on-start: true
