server:
  port: 8888
spring:
  application:
    name: config-server
  config:
    name: config-server
  sleuth:
    sampler:
      probability: 1.0

  cloud:
    config:
      server:
        git:
          uri: ${AC_CONFIG_SERVICE_GIT_REMOTE_URI}
          default-label: "develop"
          search-paths: "config-data/local"
          clone-on-start: true
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhos:8761/eureka
    instance-id:
      ${spring.application.name}:
        ${spring.application.instance_id: ${random.value}}
